dependencies:
- name: eks-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.4.0
- name: application
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.4.0
- name: activiti-cloud-modeling
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.4.0
  condition: activiti-cloud-modeling.enabled,modeling.enabled
